Repository wecode-bootcamp-korea/41-2nd-wehicle-frontend, pull requests merged in 2023-02, with the labels that each got.

#9 [41기 김진우] Modify: 리뷰 사항 수정
  package-lock.json
  package.json
  public/data/brandList.json
  public/data/productList.json
  public/images/productListPage/audi.png
  public/images/productListPage/benz.png
  public/images/productListPage/bmw.png
  public/images/productListPage/hyundai.png
  public/images/productListPage/kia.png
  public/images/productListPage/slidebar.png
  src/components/button/FilterBtn.jsx
  src/pages/productList/ProductList.js
  src/pages/productList/components/BrandNav.jsx
  src/pages/productList/components/CarBrand.jsx
  src/pages/productList/components/CarStyle.jsx
  src/pages/productList/components/OilType.jsx
  src/pages/productList/components/Options.jsx
  src/pages/productList/components/Products.jsx
  src/pages/productList/components/Size.jsx
  src/pages/productList/data/categoryData.js
Labels: 완료

#12 [41기 김진우] Add: 검색 기능 추가
  src/pages/productList/ProductList.js
  src/pages/productList/components/Products.jsx
  src/pages/productList/components/SearchBar.jsx
Labels: 수정 요청

#16 [41기 박정은] MODIFY: 로그아웃 구현 수정
  src/components/nav/Nav.js
  src/pages/payment/PaymentPoint.js
Labels: Conflict 해결 요청, Rebase 요청

#17 [41기 박정은] 디테일 페이지 MODIFY: 모달 수정
  src/pages/productDetail/ChartBox.js
  src/pages/productDetail/ProductDetail.js
  src/pages/productDetail/bidModal/BidModal.js
  src/pages/productDetail/buyModal/BuyModal.js
Labels: 완료

#18 [41기 오현주] main 리팩토링 완료
  src/pages/main/components/BrandLogo.js
  src/pages/main/components/Carousel.js
  src/pages/main/components/SecondBanner.js
  src/pages/main/components/WhatsNewCar.js
  src/pages/main/components/popularTypeCar/PopularTypeCar.js
Labels: 완료

#19 [41기 박정은] 결제페이지 수정
  src/pages/payment/Calender.js
  src/pages/payment/PaymentPoint.js
Labels: 완료
